/**
 * Bundles the MCP App view (src/app/profile-card.ts) into a single
 * self-contained HTML string and writes it to
 * src/generated/profile-card-html.ts, which src/index.ts imports and serves
 * as the ui://buffalo-projects/profile-card.html resource (MCP Apps,
 * SEP-1865). Runs before tsup/tsc/tsx — see the package.json scripts.
 *
 * The output HTML must stay self-contained (inline CSS + inline JS, no
 * external fetches): hosts render it in a sandboxed iframe with no network
 * access beyond what _meta.ui.csp allows, and we allow nothing.
 */
import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const appDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const htmlTemplatePath = join(appDir, "src/app/profile-card.html");
const appEntryPath = join(appDir, "src/app/profile-card.ts");
const outPath = join(appDir, "src/generated/profile-card-html.ts");

const bundle = await build({
  entryPoints: [appEntryPath],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
});

const js = bundle.outputFiles[0].text
  // A literal "</script>" inside the bundle would terminate the inline
  // <script> element early; escape the closing tag.
  .replaceAll("</script", "<\\/script");

const template = await readFile(htmlTemplatePath, "utf8");
const marker = "<!--__APP_SCRIPT__-->";
if (!template.includes(marker)) {
  throw new Error(`Missing ${marker} marker in ${htmlTemplatePath}`);
}
// Function replacer: a string replacement would interpret `$&`, `$'` and
// friends inside the minified bundle as substitution patterns and corrupt
// the script.
const html = template.replace(marker, () => `<script>\n${js}</script>`);

await mkdir(dirname(outPath), { recursive: true });
await writeFile(
  outPath,
  [
    "// Generated by scripts/build-app.mjs — do not edit by hand.",
    "// Self-contained MCP App view served as ui://buffalo-projects/profile-card.html.",
    `export const profileCardHtml = ${JSON.stringify(html)};`,
    "",
  ].join("\n"),
  "utf8",
);

console.log(
  `built MCP App view: ${outPath} (${(html.length / 1024).toFixed(1)} KiB)`,
);
